package com.verizon1;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Googletc1Test {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void googletc1() {
 // Test name: googletc1
 // Step # | name | target | value
 // 1 | open | / | 
 driver.get("https://www.google.com/");
 // 2 | setWindowSize | 1014x672 | 
 driver.manage().window().setSize(new Dimension(1014, 672));
 // 3 | mouseOver | linkText=About | 
 {
   WebElement element = driver.findElement(By.linkText("About"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 // 4 | click | linkText=About | 
 driver.findElement(By.linkText("About")).click();
 // 5 | close |  | 
 driver.close();
}
}
